services:
  - type: web
    name: number-plate-scanner
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./docker/Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OCR_PATH
        value: /usr/bin/tesseract
    autoDeploy: true